export default {
	colors: {
		'activityBar.background': '#000',
		'activityBar.border': '#1d1d1d',
		'activityBar.foreground': '#fff',
		'activityBarBadge.background': '#000',
		'activityBarBadge.foreground': '#fabf46',
		'badge.background': '#fabf46',
		'badge.foreground': '#000',
		'button.background': '#fabf46',
		'button.foreground': '#191324',
		'button.hoverBackground': '#9ce0e0',
		contrastBorder: '#ffffff00',
		'debugExceptionWidget.background': '#1d1d1d',
		'debugExceptionWidget.border': '#aaa',
		'debugToolBar.background': '#1d1d1d',
		descriptionForeground: '#aaa',
		'diffEditor.insertedTextBackground': '#3ad90011',
		'diffEditor.insertedTextBorder': '#3ad90055',
		'diffEditor.removedTextBackground': '#82d8d811',
		'diffEditor.removedTextBorder': '#82d8d866',
		'dropdown.background': '#000',
		'dropdown.border': '#1d1d1d',
		'dropdown.foreground': '#fff',
		'editor.background': '#000',
		'editor.findMatchBackground': '#82d8d866',
		'editor.findMatchHighlightBackground': '#82d8d866',
		'editor.findRangeHighlightBackground': '#82d8d866',
		'editor.foreground': '#eeeeeeaa',
		'editor.hoverHighlightBackground': '#362d5933',
		'editor.inactiveSelectionBackground': '#191324',
		'editor.lineHighlightBackground': '#362d5966',
		'editor.rangeHighlightBackground': '#362d5966',
		'editor.selectionBackground': '#362d5966',
		'editor.selectionHighlightBackground': '#362d59',
		'editor.wordHighlightBackground': '#FFFFFF0D',
		'editor.wordHighlightStrongBackground': '#FFFFFF0D',
		'editorBracketMatch.background': '#191324',
		'editorBracketMatch.border': '#9887b3',
		'editorCodeLens.foreground': '#aaa',
		'editorCursor.foreground': '#fff',
		'editorError.border': '#9887b3',
		'editorError.foreground': '#82d8d8',
		'editorGroup.border': '#362d59',
		'editorGroup.dropBackground': '#19132499',
		'editorGroupHeader.noTabsBackground': '#1d1d1d',
		'editorGroupHeader.tabsBackground': '#000',
		'editorGroupHeader.tabsBorder': '#362d59',
		'editorGutter.addedBackground': '#3C9F4A',
		'editorGutter.background': '#000',
		'editorGutter.deletedBackground': '#82d8d8',
		'editorGutter.modifiedBackground': '#fff',
		'editorHoverWidget.background': '#191324',
		'editorHoverWidget.border': '#362d59',
		'editorIndentGuide.background': '#3B5364',
		'editorLineNumber.foreground': '#362d59',
		'editorLink.activeForeground': '#eee',
		'editorMarkerNavigation.background': '#3B536433',
		'editorMarkerNavigationError.background': '#82d8d8',
		'editorMarkerNavigationWarning.background': '#362d59',
		'editorOverviewRuler.border': '#362d59',
		'editorOverviewRuler.commonContentForeground': '#362d5955',
		'editorOverviewRuler.currentContentForeground': '#ee3a4355',
		'editorOverviewRuler.incomingContentForeground': '#3ad90055',
		'editorRuler.foreground': '#362d59',
		'editorSuggestWidget.background': '#191324',
		'editorSuggestWidget.border': '#362d59',
		'editorSuggestWidget.foreground': '#FFF',
		'editorSuggestWidget.highlightForeground': '#03fff3',
		'editorSuggestWidget.selectedBackground': '#362d59',
		'editorWarning.border': '#362d59',
		'editorWarning.foreground': '#362d59',
		'editorWhitespace.foreground': '#ffffff',
		'editorWidget.background': '#000',
		'editorWidget.border': '#362d59',
		errorForeground: '#82d8d8',
		'extensionButton.prominentBackground': '#fabf46',
		'extensionButton.prominentForeground': '#1d1d1d',
		'extensionButton.prominentHoverBackground': '#ff9d00',
		focusBorder: '#1d1d1d',
		foreground: '#eee',
		'gitDecoration.deletedResourceForeground': '#82d8d8',
		'gitDecoration.ignoredResourceForeground': '#362d5980',
		'gitDecoration.modifiedResourceForeground': '#03fff3',
		'gitDecoration.untrackedResourceForeground': '#a8fe38',
		'input.background': '#000',
		'input.border': '#1d1d1d',
		'input.foreground': '#eee',
		'input.placeholderForeground': '#aaa',
		'inputOption.activeBorder': '#362d59',
		'inputValidation.errorBackground': '#191324',
		'inputValidation.errorBorder': '#362d59dd',
		'inputValidation.infoBackground': '#191324',
		'inputValidation.infoBorder': '#191324',
		'inputValidation.warningBackground': '#191324',
		'inputValidation.warningBorder': '#362d59',
		'list.activeSelectionBackground': '#fabf46',
		'list.activeSelectionForeground': '#191324',
		'list.deemphasizedForeground': '#191324',
		'list.dropBackground': '#191324',
		'list.filterMatchBackground': '#fff',
		'list.focusBackground': '#fabf4688',
		'list.focusForeground': '#eee',
		'list.highlightForeground': '#ffffff99',
		'list.hoverBackground': '#fabf4688',
		'list.hoverForeground': '#fff',
		'list.inactiveSelectionBackground': '#fabf46',
		'list.inactiveSelectionForeground': '#191324',
		'merge.border': '#ffffff00',
		'merge.commonContentBackground': '#ffffff00',
		'merge.commonHeaderBackground': '#ffffff00',
		'merge.currentContentBackground': '#ffffff00',
		'merge.currentHeaderBackground': '#ffffff00',
		'merge.incomingContentBackground': '#ffffff00',
		'merge.incomingHeaderBackground': '#ffffff00',
		'panel.background': '#000',
		'panel.border': '#1d1d1d',
		'panelTitle.activeBorder': '#1d1d1d',
		'panelTitle.activeForeground': '#1d1d1d',
		'panelTitle.inactiveForeground': '#aaa',
		'peekView.border': '#191324',
		'peekViewEditor.background': '#191324',
		'peekViewEditor.matchHighlightBackground': '#191324',
		'peekViewEditorGutter.background': '#191324',
		'peekViewResult.background': '#191324',
		'peekViewResult.fileForeground': '#aaa',
		'peekViewResult.lineForeground': '#fff',
		'peekViewResult.matchHighlightBackground': '#191324',
		'peekViewResult.selectionBackground': '#191324',
		'peekViewResult.selectionForeground': '#fff',
		'peekViewTitle.background': '#191324',
		'peekViewTitleDescription.foreground': '#aaa',
		'peekViewTitleLabel.foreground': '#362d59',
		'pickerGroup.border': '#1d1d1d',
		'pickerGroup.foreground': '#aaa',
		'progressBar.background': '#1d1d1d',
		'quickInput.background': '#000',
		'quickInput.foreground': '#fff',
		'scrollbar.shadow': '#000',
		'scrollbarSlider.activeBackground': '#fabf46',
		'scrollbarSlider.background': '#fabf4680',
		'scrollbarSlider.hoverBackground': '#fabf46',
		'selection.background': '#fabf46',
		'sideBar.background': '#000',
		'sideBar.border': '#362d5966',
		'sideBar.foreground': '#ffffffcc',
		'sideBarSectionHeader.background': '#1d1d1d',
		'sideBarSectionHeader.foreground': '#fff',
		'sideBarTitle.foreground': '#eee',
		'statusBar.background': '#000',
		'statusBar.border': '#1d1d1d',
		'statusBar.debuggingBackground': '#1d1d1d',
		'statusBar.debuggingForeground': '#191324',
		'statusBar.foreground': '#eee',
		'statusBar.noFolderBackground': '#1d1d1d',
		'statusBar.noFolderForeground': '#eee',
		'statusBarItem.activeBackground': '#fabf46',
		'statusBarItem.hoverBackground': '#1d1d1d',
		'statusBarItem.prominentBackground': '#191324',
		'statusBarItem.prominentHoverBackground': '#191324',
		'tab.activeBackground': '#1d1d1d',
		'tab.activeBorder': '#fabf46',
		'tab.activeForeground': '#fabf46',
		'tab.border': '#362d59',
		'tab.inactiveBackground': '#000',
		'tab.inactiveForeground': '#aaa',
		'tab.unfocusedActiveForeground': '#aaa',
		'tab.unfocusedInactiveForeground': '#aaa',
		'terminal.ansiBlack': '#000',
		'terminal.ansiBlue': '#03fff3',
		'terminal.ansiBrightBlack': '#0050A4',
		'terminal.ansiBrightBlue': '#03fff3',
		'terminal.ansiBrightCyan': '#80fcff',
		'terminal.ansiBrightGreen': '#3ad900',
		'terminal.ansiBrightMagenta': '#82d8d8',
		'terminal.ansiBrightRed': '#ff628c',
		'terminal.ansiBrightWhite': '#191324',
		'terminal.ansiBrightYellow': '#362d59',
		'terminal.ansiCyan': '#80fcff',
		'terminal.ansiGreen': '#3ad900',
		'terminal.ansiMagenta': '#82d8d8',
		'terminal.ansiRed': '#ff628c',
		'terminal.ansiWhite': '#ffffff',
		'terminal.ansiYellow': '#362d59',
		'terminal.background': '#1d1d1d',
		'terminal.foreground': '#ffffff',
		'terminalCursor.background': '#362d59',
		'terminalCursor.foreground': '#362d59',
		'textBlockQuote.background': '#191324',
		'textBlockQuote.border': '#03fff3',
		'textCodeBlock.background': '#191324',
		'textLink.activeForeground': '#03fff3',
		'textLink.foreground': '#03fff3',
		'textPreformat.foreground': '#362d59',
		'textSeparator.foreground': '#191324',
		'titleBar.activeBackground': '#000',
		'titleBar.activeForeground': '#aaa',
		'titleBar.inactiveBackground': '#000',
		'titleBar.inactiveForeground': '#aaa',
		'walkThrough.embeddedEditorBackground': '#191324',
	},
	name: 'syntax',
	tokenColors: [
		{
			name: 'Comment',
			scope: ['comment', 'punctuation.definition.comment'],
			settings: {
				fontStyle: 'italic',
				foreground: '#03fff3',
			},
		},
		{
			name: 'Constant',
			scope: 'constant',
			settings: {
				foreground: '#ff628c',
			},
		},
		{
			name: 'Entity',
			scope: 'entity',
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: 'Invalid',
			scope: 'invalid',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: 'Keyword',
			scope: 'keyword, storage.type.class.js',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: 'Meta',
			scope: 'meta',
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: 'Meta Brace',
			scope: 'meta.brace',
			settings: {
				foreground: '#9588aa',
			},
		},
		{
			name: 'Punctuation',
			scope: 'punctuation',
			settings: {
				foreground: '#9588aa',
			},
		},
		{
			name: 'Punctuation Parameters',
			scope: 'punctuation.definition.parameters',
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: 'Punctuation Template Expression',
			scope: 'punctuation.definition.template-expression',
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: 'Storage',
			scope: 'storage',
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: 'SFunction',
			scope: ['entity.name.function', 'entity.name.method'],
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: 'Storage Type Arrow Function',
			scope: 'storage.type.function.arrow',
			settings: {
				foreground: '#fabf46',
			},
		},
		{
			name: 'String',
			scope: ['string', 'punctuation.definition.string'],
			settings: {
				foreground: '#fabf46',
			},
		},
		{
			name: 'String Template',
			scope: ['string.template', 'punctuation.definition.string.template'],
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: 'Support',
			scope: 'support',
			settings: {
				foreground: '#ff25be',
			},
		},
		{
			name: 'Property',
			scope: ['support.type.property-name', 'variable.name'],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: 'Support Function',
			scope: 'support.function',
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: 'Support Variable Property DOM',
			scope: 'support.variable.property.dom',
			settings: {
				foreground: '#eeeeee',
			},
		},
		{
			name: 'Variable',
			scope: 'variable',
			settings: {
				foreground: '#ff25be',
			},
		},
		{
			name: '[CSS] - Entity',
			scope: ['source.css entity', 'source.stylus entity'],
			settings: {
				foreground: '#b8b0c6',
			},
		},
		{
			name: '[CSS] - ID Selector',
			scope: 'entity.other.attribute-name.id.css',
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[CSS] - Element Selector',
			scope: 'entity.name.tag',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: '[CSS] - Support',
			scope: ['source.css support', 'source.stylus support'],
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: '[CSS] - Constant',
			scope: [
				'source.css constant',
				'source.css support.constant',
				'source.stylus constant',
				'source.stylus support.constant',
			],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[CSS] - String',
			scope: [
				'source.css string',
				'source.css punctuation.definition.string',
				'source.stylus string',
				'source.stylus punctuation.definition.string',
			],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[CSS] - Variable',
			scope: ['source.css variable', 'source.stylus variable'],
			settings: {
				foreground: '#9588aa',
			},
		},
		{
			name: '[HTML] - Entity Name',
			scope: 'text.html.basic entity.name',
			settings: {
				foreground: '#9588aa',
			},
		},
		{
			name: '[HTML] - ID value',
			scope: 'meta.toc-list.id.html',
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: '[HTML] - Entity Other',
			scope: 'text.html.basic entity.other',
			settings: {
				fontStyle: 'italic',
				foreground: '#eee',
			},
		},
		{
			name: '[HTML] - Script Tag',
			scope: 'meta.tag.metadata.script.html entity.name.tag.html',
			settings: {
				foreground: '#eee',
			},
		},
		{
			name: '[HTML] - Quotes. these are a slightly different colour because expand selection will then not include quotes',
			scope: 'punctuation.definition.string.begin, punctuation.definition.string.end',
			settings: {
				foreground: '#92fc79',
			},
		},
		{
			name: '[INI] - Entity',
			scope: 'source.ini entity',
			settings: {
				foreground: '#e1efff',
			},
		},
		{
			name: '[INI] - Keyword',
			scope: 'source.ini keyword',
			settings: {
				foreground: '#362d59',
			},
		},
		{
			name: '[INI] - Punctuation Definition',
			scope: 'source.ini punctuation.definition',
			settings: {
				foreground: '#ffee80',
			},
		},
		{
			name: '[INI] - Punctuation Separator',
			scope: 'source.ini punctuation.separator',
			settings: {
				foreground: '#ff9d00',
			},
		},
		{
			name: '[JAVASCRIPT] - Storage Type Function',
			scope: 'source.js storage.type.function',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: '[JAVASCRIPT] - Variable Language',
			scope: 'variable.language, entity.name.type.class.js',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: '[JAVASCRIPT] - Inherited Component',
			scope: 'entity.other.inherited-class.js',
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: '[PYTHON] - Self Argument',
			scope: 'variable.parameter.function.language.special.self.python',
			settings: {
				foreground: '#82d8d8',
			},
		},
		{
			name: '[JSON] - Support',
			scope: 'source.json support',
			settings: {
				foreground: '#b8b0c6',
			},
		},
		{
			name: '[JSON] - String',
			scope: ['source.json string', 'source.json punctuation.definition.string'],
			settings: {
				foreground: '#e1efff',
			},
		},
		{
			name: '[MARKDOWN] - Heading Punctuation',
			scope: 'punctuation.definition.heading.markdown',
			settings: {
				foreground: '#e1efff',
			},
		},
		{
			name: '[MARKDOWN] - Heading Name Section',
			scope: [
				'entity.name.section.markdown',
				'markup.heading.setext.1.markdown',
				'markup.heading.setext.2.markdown',
			],
			settings: {
				fontStyle: 'bold',
				foreground: '#82d8d8',
			},
		},
		{
			name: '[MARKDOWN] - Paragraph',
			scope: 'meta.paragraph.markdown',
			settings: {
				foreground: '#e1efff',
			},
		},
		{
			name: '[MARKDOWN] - Quote Punctuation',
			scope: 'beginning.punctuation.definition.quote.markdown',
			settings: {
				foreground: '#362d59',
			},
		},
		{
			name: '[MARKDOWN] - Quote Paragraph',
			scope: 'markup.quote.markdown meta.paragraph.markdown',
			settings: {
				fontStyle: 'italic',
				foreground: '#03fff3',
			},
		},
		{
			name: '[MARKDOWN] - Separator',
			scope: 'meta.separator.markdown',
			settings: {
				foreground: '#362d59',
			},
		},
		{
			name: '[MARKDOWN] - Emphasis Bold',
			scope: 'markup.bold.markdown',
			settings: {
				fontStyle: 'bold',
				foreground: '#03fff3',
			},
		},
		{
			name: '[MARKDOWN] - Emphasis Italic',
			scope: 'markup.italic.markdown',
			settings: {
				fontStyle: 'italic',
				foreground: '#03fff3',
			},
		},
		{
			name: '[MARKDOWN] - Lists',
			scope: 'beginning.punctuation.definition.list.markdown',
			settings: {
				foreground: '#362d59',
			},
		},
		{
			name: '[MARKDOWN] - Link Title',
			scope: 'string.other.link.title.markdown',
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: '[MARKDOWN] - Link/Image Title',
			scope: [
				'string.other.link.title.markdown',
				'string.other.link.description.markdown',
				'string.other.link.description.title.markdown',
			],
			settings: {
				foreground: '#a8fe38',
			},
		},
		{
			name: '[MARKDOWN] - Link Address',
			scope: ['markup.underline.link.markdown', 'markup.underline.link.image.markdown'],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[MARKDOWN] - Inline Code',
			scope: ['fenced_code.block.language', 'markup.inline.raw.markdown'],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[MARKDOWN] - Code Block',
			scope: ['fenced_code.block.language', 'markup.inline.raw.markdown'],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[GRAPHQL] - Type',
			scope: ['support.type.builtin.graphql'],
			settings: {
				foreground: '#03fff3',
			},
		},
		{
			name: '[TYPESCRIPT] - Comment',
			scope: ['punctuation.definition.comment.ts', 'comment.line.double-slash.ts'],
			settings: {
				foreground: '#ffffff33',
			},
		},
		{
			name: '[TYPESCRIPT] - Comment',
			scope: ['punctuation.definition.comment', 'comment.line.double-slash'],
			settings: {
				foreground: '#ffffff33',
			},
		},
		{
			name: '[JS,TS] - Storage',
			scope: ['storage.type', 'meta.var.expr'],
			settings: {
				foreground: '#eeeeeeaa',
			},
		},
		{
			name: '[TYPESCRIPT] - type keyword',
			scope: ['storage.type.type.ts', 'meta.type.declaration.ts'],
			settings: {
				foreground: '#fabf46',
			},
		},
	],
	type: 'dark',
};
